---
title: "Project browsing"
author: "Jake Becker"
date: "11/24/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(MASS)
library(caret)
library(class)
athlete_events = read.csv("C:/Users/jakeb/OneDrive/Documents/DSCI 445/athlete_events.csv")
set.seed(445)
```

```{r}
athlete_events %>%
  ggplot() + 
  geom_point(aes(x = Weight,
                 y = Height,
                 col = Medal))
```

```{r}
athlete_events %>%
  ggplot() + 
  geom_boxplot(aes(x = Medal,
                   y = Age,
                   col = Medal))
```

```{r}
athlete_events %>%
  filter(Sport == 'Speed Skating') %>%
  ggplot() + 
  geom_point(aes(x = Height,
                 y = Weight,
                 col = Medal))
```

```{r}
athlete_events %>%
  group_by(Medal, Sex) %>%
  summarize(H = mean(Height, na.rm = TRUE), 
            W = mean(Weight, na.rm = TRUE),
            A = mean(Age, na.rm = TRUE))
length(unique(athlete_events$Sport))
```

```{r}
bobsled = athlete_events %>%
  filter(Sport == 'Bobsleigh' & Sex == 'M')

bobsled %>%
  ggplot() + 
  geom_point(aes(x = Weight,
                 y = Height,
                 col = Medal))
```

```{r}
bobsled %>%
  ggplot() + 
  geom_boxplot(aes(x = Medal,
                   y = Age,
                   col = Medal))
```

```{r}
bobsled %>%
  ggplot() + 
  geom_point(aes(x = Height,
                 y = Weight)) + 
  facet_wrap('Medal')
```

```{r}
bobsled %>%
  group_by(Medal) %>%
  summarize(H = mean(Height, na.rm = TRUE), 
            W = mean(Weight, na.rm = TRUE),
            A = mean(Age, na.rm = TRUE))
```

```{r}
bobsledT = bobsled %>%
  mutate(Weight = Weight * 2.2,
         Medal = ifelse(is.na(Medal) == TRUE, 'DNM', Medal)) %>%
  filter(Year != 2014)

bobpredbin = bobsled %>%
  mutate(Medal = ifelse(Medal =='DNM', 0, 1))

bobbin = bobsledT %>%
  mutate(Medal = ifelse(Medal == 'DNM', 0, 1))
```

```{r}
samples = sample(nrow(bobsledT), nrow(bobsledT) * .8)
bobtrain = na.omit(bobsledT[samples,])
bobtest = na.omit(bobsledT[-samples,])
#bobLDA = qda(Medal ~ Age + Height + Weight, data = bobtrain)
#table(actual = bobtest$Medal, predicted = predict(bobLDA, newdata = bobtest)$class)
```

```{r}
knntrain = na.omit(bobbin[samples,])
knntest = na.omit(bobbin[-samples,])
bobknn = knn3(Medal ~ Age + Height + Weight, data = knntrain, k = 3)
bobpred = predict(bobknn, newdata = knntest)
bobpredvec = c(ifelse(bobpred[,1] > .5, 0, 1))
table(knntest$Medal, bobpredvec)
```


```{r probit model}
probit = polr(as.factor(Medal) ~ Age + Weight + Height, data = bobtrain, Hess = TRUE)
probpred = predict(probit, newdata = bobsled14, type = 'probs')
summary(probit)
probitDf = cbind(bobsled14, probpred)
probitDf %>% 
  filter(Event == "Bobsleigh Men's Four") %>%
  mutate(MedalProb = Gold + Silver + Bronze) %>% 
  group_by(Team) %>%
  summarize(Win = sum(MedalProb)) %>%
  arrange(Win)
```

```{r}
probitDf %>% 
  filter(Event == "Bobsleigh Men's Two") %>%
  mutate(MedalProb = Gold + Silver + Bronze) %>% 
  group_by(Team) %>%
  summarize(Win = sum(MedalProb)) %>%
  arrange(Win)
```


```{r resultsfour}
probitDf %>% 
  filter(Event == "Bobsleigh Men's Four") %>%
  mutate(MedalProb = Gold + Silver + Bronze) %>% 
  group_by(Team) %>%
  ggplot() + 
  geom_point(aes(x = Height,
                 y = Weight,
                 col = MedalProb))
```

```{r twomanresults}
probitDf %>% 
  filter(Event == "Bobsleigh Men's Two") %>%
  mutate(MedalProb = Gold + Silver + Bronze) %>% 
  group_by(Team) %>%
  ggplot() + 
  geom_point(aes(x = Height,
                 y = Weight,
                 col = MedalProb))
```

